name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      env : 
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run : |

        - name: Generate tags
        id: docker_tags
        uses: dnaka91/action-docker-tags@v0.1
        with:
          registries: |
            docker.io
            ghcr.io
            quay.io

    - run: docker push ${{secrets.DOCKER_USER}}/cluster-hadoop-singlenode:testhadoop
    
        
         
         


